name: setup
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: make setup
      - run: make install
      - run: make lint
      - name: run tests
        run: make test
